artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Sanju-Shrestha/SummarizeMe/raw/refs/heads/main/data/summarizme-data.zip
  local-data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion